name: CI Automation

on: 
  push: 
  pull_request: 
  schedule:
    - cron: '0 0 * * *' # Run every day at 00:00 UTC

jobs:
  run_pandas_josb:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Specify the Python version you need

      - name: Setup Docker
        uses: docker/setup-buildx-action@v3


      - name: Install dependencies
        run: pip install pandas
        

      - name: Run app.py
        run: python app.py